apiVersion: apps/v1
kind: Deployment
metadata:
  name: sudoku-app
  namespace: sudoku
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sudoku
  template:
    metadata:
      labels:
        app: sudoku
    spec:
      containers:
      - name: sudoku
        image: ghcr.io/pilgrimv/sudoku-web-test
        imagePullPolicy: Always
        tag: 1.0.1
        ports:
        - containerPort: 5000
      imagePullSecrets:
      - name: ghcr-secret

